In [38]:
import pandas as pd

In [39]:
student_life_df = pd.read_csv('../Data/AI_Impact_Student_Life_2026.csv')
jobs_df = pd.read_csv('../Data/ai_job_impact.csv')
content_df = pd.read_csv('../Data/Global_AI_Content_Impact_Dataset.csv')

In [40]:
student_life_df.head()

,Student_ID,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9

In [41]:
student_life_df.tail(10)

,Student_ID,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score
1490,STU-0866,23,Fine Arts,GitHub Copilot,7,Code Debugging,3.60,3.80,15,Medium,3
1491,STU-4535,18,Software Engineering,Gemini Pro,2,Brainstorming,3.73,3.93,9,Medium,5
1492,STU-4908,24,Software Engineering,GitHub Copilot,9,Essay Drafting,3.14,3.44,6,Medium,9
1493,STU-2710,25,Modern History,Gemini Pro,2,Essay Drafting,2.74,2.74,6,Low,1
1494,STU-5328,20,Fine Arts,Gemini Pro,5,Code Debugging,3.36,3.56,14,High,3
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8

In [42]:
student_life_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               1500 non-null   str
 1   Age                      1500 non-null   int64
 2   Major                    1500 non-null   str
 3   Primary_AI_Tool          1500 non-null   str
 4   Task_Frequency_Daily     1500 non-null   int64
 5   Main_Usage_Case          1500 non-null   str
 6   GPA_Baseline             1500 non-null   float64
 7   GPA_Post_AI              1500 non-null   float64
 8   Time_Saved_Hours_Weekly  1500 non-null   int64
 9   AI_Ethics_Concern        1500 non-null   str
 10  Career_Confidence_Score  1500 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 129.0 KB

In [43]:
student_life_df.shape

(1500, 11)

In [44]:
jobs_df.head()

,Employee_ID,Age,Gender,Education_Level,Industry,Job_Role,Years_Experience,AI_Adoption_Level,Automation_Risk,Upskilling_Required,Salary_Before_AI,Salary_After_AI,Job_Status,Work_Hours_Per_Week,Remote_Work,Job_Satisfaction,Productivity_Change_%
0,E0001,50,Female,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64
1,E0002,45,Male,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05
2,E0003,51,Female,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05
3,E0004,48,Male,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47
4,E0005,24,Male,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03

In [45]:
jobs_df.tail()

,Employee_ID,Age,Gender,Education_Level,Industry,Job_Role,Years_Experience,AI_Adoption_Level,Automation_Risk,Upskilling_Required,Salary_Before_AI,Salary_After_AI,Job_Status,Work_Hours_Per_Week,Remote_Work,Job_Satisfaction,Productivity_Change_%
1995,E1996,55,Other,PhD,Healthcare,Technician,30,Medium,Low,Yes,99082,101090,Unchanged,52,Yes,7,25.67
1996,E1997,31,Male,PhD,Finance,Investment Analyst,9,High,Medium,Yes,32379,44653,Modified,52,Yes,8,9.38
1997,E1998,43,Female,Bachelor,Retail,Cashier,17,High,High,No,53424,74715,Modified,49,Yes,6,-0.57
1998,E1999,43,Female,Bachelor,Marketing,Digital Marketer,20,Medium,Low,No,57821,68499,Unchanged,41,No,9,9.31
1999,E2000,23,Other,Master,Marketing,SEO Specialist,0,High,High,Yes,33830,34809,Modified,37,Yes,9,24.40

In [46]:
jobs_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            2000 non-null   str
 1   Age                    2000 non-null   int64
 2   Gender                 2000 non-null   str
 3   Education_Level        2000 non-null   str
 4   Industry               2000 non-null   str
 5   Job_Role               2000 non-null   str
 6   Years_Experience       2000 non-null   int64
 7   AI_Adoption_Level      2000 non-null   str
 8   Automation_Risk        2000 non-null   str
 9   Upskilling_Required    2000 non-null   str
 10  Salary_Before_AI       2000 non-null   int64
 11  Salary_After_AI        2000 non-null   int64
 12  Job_Status             2000 non-null   str
 13  Work_Hours_Per_Week    2000 non-null   int64
 14  Remote_Work            2000 non-null   str
 15  Job_Satisfaction       2000 non-null   int64
 16  Productivity_Change_%  2000 non-null   float64
dtypes: float64(1), int64(6), str(10)
memory usage: 265.8 KB

In [47]:
jobs_df.shape

(2000, 17)

In [48]:
content_df.head()

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [49]:
content_df.tail()

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37

In [50]:
content_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     200 non-null    str
 1   Year                                        200 non-null    int64
 2   Industry                                    200 non-null    str
 3   AI Adoption Rate (%)                        200 non-null    float64
 4   AI-Generated Content Volume (TBs per year)  200 non-null    float64
 5   Job Loss Due to AI (%)                      200 non-null    float64
 6   Revenue Increase Due to AI (%)              200 non-null    float64
 7   Human-AI Collaboration Rate (%)             200 non-null    float64
 8   Top AI Tools Used                           200 non-null    str
 9   Regulation Status                           200 non-null    str
 10  Consumer Trust in AI (%)                    200 non-null    float64
 11  Market Share of AI Companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), str(4)
memory usage: 18.9 KB

In [51]:
content_df.shape

(200, 12)

In [52]:
student_life_df[['GPA_Baseline', 'GPA_Post_AI']]

      GPA_Baseline  GPA_Post_AI
0             2.62         2.62
1             3.99         4.00
2             2.57         2.57
3             2.67         2.87
4             3.65         3.85
...            ...          ...
1495          3.35         3.55
1496          3.59         3.89
1497          3.20         3.40
1498          3.99         4.00
1499          3.53         3.43

[1500 rows x 2 columns]

In [53]:
GPA_growth_df = student_life_df[student_life_df['GPA_Baseline'] < student_life_df['GPA_Post_AI']]
GPA_growth_df.shape

(894, 11)

In [54]:
GPA_decline_df = student_life_df[student_life_df['GPA_Baseline'] > student_life_df['GPA_Post_AI']]
GPA_decline_df.shape

(301, 11)

In [55]:
GPA_same_df = student_life_df[student_life_df['GPA_Baseline'] == student_life_df['GPA_Post_AI']]
GPA_same_df.shape

(305, 11)

In [56]:
student_life_df.describe()

,Age,Task_Frequency_Daily,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,Career_Confidence_Score
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000,1500.000000
mean,21.494000,5.407333,3.256853,3.344587,8.51000,5.417333
std,2.297277,2.905462,0.430583,0.437409,4.07148,2.844977
min,18.000000,1.000000,2.500000,2.400000,2.00000,1.000000
25%,20.000000,3.000000,2.880000,2.980000,5.00000,3.000000
50%,21.000000,5.000000,3.260000,3.360000,9.00000,5.000000
75%,23.000000,8.000000,3.620000,3.710000,12.00000,8.000000
max,25.000000,10.000000,4.000000,4.000000,15.00000,10.000000

In [57]:
student_life_df['Primary_AI_Tool'].value_counts()

Primary_AI_Tool
GitHub Copilot    311
Gemini Pro        302
Perplexity        302
Claude 3.5        297
ChatGPT-4o        288
Name: count, dtype: int64

In [58]:
jobs_df.describe()

,Age,Years_Experience,Salary_Before_AI,Salary_After_AI,Work_Hours_Per_Week,Job_Satisfaction,Productivity_Change_%
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,40.558000,16.663500,73942.072500,78428.642500,44.85100,6.020500,9.785820
std,10.786418,10.746675,26055.823793,29351.599013,5.71254,2.006263,17.187882
min,22.000000,0.000000,30036.000000,24447.000000,35.00000,3.000000,-19.990000
25%,32.000000,8.000000,51665.500000,54086.750000,40.00000,4.000000,-5.355000
50%,40.000000,16.000000,74620.000000,76820.500000,45.00000,6.000000,9.850000
75%,50.000000,26.000000,95418.250000,100730.250000,50.00000,8.000000,24.582500
max,59.000000,37.000000,119976.000000,161745.000000,54.00000,9.000000,39.990000

In [59]:
def categorize_experience(Years_Experience):
    if Years_Experience <= 2:
        return 'Entry Level'
    elif Years_Experience >= 3 and Years_Experience < 5:
        return 'Mid Level'
    else:
        return 'Senior'

jobs_df['ExperienceLevel'] = jobs_df['Years_Experience'].apply(categorize_experience)

In [60]:
jobs_df.head()

,Employee_ID,Age,Gender,Education_Level,Industry,Job_Role,Years_Experience,AI_Adoption_Level,Automation_Risk,Upskilling_Required,Salary_Before_AI,Salary_After_AI,Job_Status,Work_Hours_Per_Week,Remote_Work,Job_Satisfaction,Productivity_Change_%,ExperienceLevel
0,E0001,50,Female,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior
1,E0002,45,Male,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior
2,E0003,51,Female,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior
3,E0004,48,Male,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior
4,E0005,24,Male,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level

In [61]:
jobs_df['Gender'] = jobs_df['Gender'].map({'Male': 'M', 'Female': 'F', 'Other': 'O'})

jobs_df.head()

,Employee_ID,Age,Gender,Education_Level,Industry,Job_Role,Years_Experience,AI_Adoption_Level,Automation_Risk,Upskilling_Required,Salary_Before_AI,Salary_After_AI,Job_Status,Work_Hours_Per_Week,Remote_Work,Job_Satisfaction,Productivity_Change_%,ExperienceLevel
0,E0001,50,F,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior
1,E0002,45,M,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior
2,E0003,51,F,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior
3,E0004,48,M,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior
4,E0005,24,M,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level

In [62]:
jobs_df['Gender'] = jobs_df['Gender'].map({'M': 'Male', 'F': 'Female', 'O': 'Other'})

jobs_df.head()

,Employee_ID,Age,Gender,Education_Level,Industry,Job_Role,Years_Experience,AI_Adoption_Level,Automation_Risk,Upskilling_Required,Salary_Before_AI,Salary_After_AI,Job_Status,Work_Hours_Per_Week,Remote_Work,Job_Satisfaction,Productivity_Change_%,ExperienceLevel
0,E0001,50,Female,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior
1,E0002,45,Male,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior
2,E0003,51,Female,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior
3,E0004,48,Male,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior
4,E0005,24,Male,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level